test:
	@echo "Running time tests..."
	@echo "================ NQueens ================"
	@./timer.sh NQ   0 13     2  1
	@echo "=============== Fibonacci ==============="
	@./timer.sh FIB  0 5000   75 100
	@echo "============== StressTest ==============="
	@./timer.sh STRS 0 500000 50 10000
	@echo "========================================="
