test:
	@echo "Running time tests..."
	@echo "================ NQueens ================"
	@./timer.sh NQ   0 15     1  1
	@echo "=============== Fibonacci ==============="
	@./timer.sh FIB  0 5000   25 100
	@echo "============== StressTest ==============="
	@./timer.sh STRS 0 500000 10 10000
	@echo "========================================="
