install_eff:
	git clone git@github.com:reilem/eff.git
	cd eff
	./configure
	make
	sudo make install

compile_run:
	eff Memoization/fibonacci.eff
	@echo ""
	eff NQueens/nqueens.eff
	@echo ""
	eff Parser/parser.eff
	@echo ""
	eff Pipes/pipes.eff
	@echo ""
	eff StressTest/stresstest.eff
	@echo ""
	eff TreeAlgorithm/fringe.eff
